Repository 1OS-DevTeam/TodoPang, pull requests merged in 2023-12, with the labels that each got.

#51 [feat] bind data to ChallengeView and add ChallengeAlert
  teamplan/Resources/Assets.xcassets/Colors/MainPurpleColor.colorset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/lock_icon.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/lock_icon.imageset/lock_icon.png
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/lock_icon.imageset/lock_icon@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/lock_icon.imageset/lock_icon@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/plus_circle.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/plus_circle.imageset/plus_circle.png
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/plus_circle.imageset/plus_circle@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Icons/plus_circle.imageset/plus_circle@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/add_challenge_text.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/add_challenge_text.imageset/add_challeng_text.png
  teamplan/Resources/Assets.xcassets/Images/Home/add_challenge_text.imageset/add_challeng_text@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/add_challenge_text.imageset/add_challeng_text@3x.png
  teamplan/Sources/Extensions/Array+Extension.swift
  teamplan/Sources/Extensions/View+Extension.swift
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeObject.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
  teamplan/Sources/Views/Alert/ChallengeAlertModifier.swift
  teamplan/Sources/Views/Alert/ChallengeAlertView.swift
  teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardBackView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardFrontView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeDetailView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeEmptyView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeExampleView.swift
  teamplan/Sources/Views/Home/HomeView.swift
Labels: For: iOS Dev, Priority: Medium, Status: In Progress, Type: Feature

#53 [Refact] DTO & Object 개편
  teamplan/Resources/Storage/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
  teamplan/Sources/Object/Authentication/AuthDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeObject.swift
  teamplan/Sources/Object/Log/AccessLog.swift
  teamplan/Sources/Object/Log/ChallengeLog.swift
  teamplan/Sources/Object/Project/ProjectDTO.swift
  teamplan/Sources/Object/Project/ProjectObject.swift
  teamplan/Sources/Object/Statistics/StatisticsDTO.swift
  teamplan/Sources/Object/Statistics/StatisticsObject.swift
  teamplan/Sources/Object/User/UserDTO.swift
  teamplan/Sources/Object/User/UserObject.swift
  teamplan/Sources/Services/Challenge/ChallengeManager.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
  teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/SignupService.swift
  teamplan/Sources/Services/Statistics/StatisticsCenter.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
  teamplan/Sources/Util/CoreDataManager.swift
  teamplan/Sources/Util/Utilities.swift
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#54 [feat] Refact & Add Feature at 'LoginLoadingService'
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeObject.swift
  teamplan/Sources/Object/Log/ChallengeLog.swift
  teamplan/Sources/Services/Challenge/ChallengeManager.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
Labels: For: iOS Dev, Priority: High, Status: Review Needed, Type: Feature
