Repository 1OS-DevTeam/TodoPang, pull requests merged in 2023-11, with the labels that each got.

#39 [refact] 'SignupLoadingService' 리팩토링 및 기능추가
  teamplan/Resources/Storage/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeObject.swift
  teamplan/Sources/Object/Log/AccessLog.swift
  teamplan/Sources/Object/Log/ChallengeLog.swift
  teamplan/Sources/Object/Statistics/StatisticsObject.swift
  teamplan/Sources/Object/User/UserDTO.swift
  teamplan/Sources/Object/User/UserObject.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
  teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/SignupService.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
  teamplan/Sources/Services/User/UserServicesCoredata.swift
  teamplan/Sources/Services/User/UserServicesFirestore.swift
  teamplan/Sources/Util/Utilities.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#41 [Fix] Refact 'Statistics' related
  teamplan/Sources/Object/Statistics/StatisticsDTO.swift
  teamplan/Sources/Object/Statistics/StatisticsObject.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Util/Utilities.swift
Labels: For: iOS Dev, Priority: High, Status: Review Needed, Type: Bug

#43 [Refact] 'HomeService' & 'ChallengeService'
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Log/ChallengeLog.swift
  teamplan/Sources/Object/Project/ProjectDTO.swift
  teamplan/Sources/Object/Statistics/StatisticsDTO.swift
  teamplan/Sources/Object/User/UserPhrase.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/Statistics/StatisticsCenter.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
Labels: For: iOS Dev, Priority: High, Status: Review Needed, Type: Feature

#44 [feat] Add missing function to 'ChallengeService' & 'ChallengeDTO'
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
Labels: For: iOS Dev, Priority: High, Status: Review Needed, Type: Feature

#46 [Refact] 'LoginLoadingService' & Storage Related & Etc
  teamplan/Sources/Archive/LoginLoadingServiceOld.swift
  teamplan/Sources/Object/Log/AccessLog.swift
  teamplan/Sources/Object/Statistics/StatisticsDTO.swift
  teamplan/Sources/Object/User/UserDTO.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
  teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
  teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/SignupService.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
  teamplan/Sources/Services/User/UserServicesCoredata.swift
  teamplan/Sources/Services/User/UserServicesFirestore.swift
  teamplan/Sources/Util/Utilities.swift
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
Labels: For: iOS Dev, Priority: High, Status: Review Needed, Type: Feature

#48 [feat] add fetching user from Firestore
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
  teamplan/Sources/Views/Authentication/LoginView.swift
  teamplan/Sources/Views/Home/HomeView.swift
  teamplan/Sources/Views/Onboarding/IntroView.swift
Labels: For: DB/API, For: iOS Dev, Priority: Medium, Status: In Progress, Type: Bug

#49 [Refact] Add 'ChallengeManager' & Etc
  teamplan/Sources/Object/Challenge/ChallengeObject.swift
  teamplan/Sources/Object/Statistics/StatisticsObject.swift
  teamplan/Sources/Services/Challenge/ChallengeManager.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesFirestore.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/Dummy/GenerateDummy.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
  teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/Statistics/StatisticsCenter.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
  teamplan/Sources/Services/User/UserServicesCoredata.swift
  teamplan/Sources/Services/User/UserServicesFirestore.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#50 [feat] binding data to HomeView
  teamplan/Sources/Object/User/UserObject.swift
  teamplan/Sources/Services/Authentication/AuthGoogleServices.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
  teamplan/Sources/Views/Home/ChallengeCardView.swift
  teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardBackView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardFrontView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeDetailView.swift
  teamplan/Sources/Views/Home/HomeView.swift
Labels: For: iOS Dev, Priority: Low, Status: In Progress, Type: Feature
