Repository 1OS-DevTeam/TodoPang, pull requests merged in 2024-02, with the labels that each got.

#67 [feat] Add logging point at 'SignupLoadingService' & add new log parameter at 'LogManager'
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/Log/LogManager.swift
  teamplan/Sources/Services/Login/SynchronizeLocal.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#72 [update] Rework 'ChallengeService' & challenge related in 'LocalSynchronizer'
  teamplan/Sources/Object/Authentication/AuthDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/Log/LogManager.swift
  teamplan/Sources/Services/Login/AuthGoogleServices.swift
  teamplan/Sources/Services/Login/SynchronizeLocal.swift
  teamplan/Sources/Services/LoginService.swift
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
  teamplan/Sources/Views/Authentication/LoginView.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#75 [Update] Add description & code repositioning at Service
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/Synchronize/SyncLocaltoServer.swift
  teamplan/Sources/Services/Synchronize/SyncServerToLocal.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Refactoring

#76 [feat] Add Project Views
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_done.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_done.imageset/checkBox_done.png
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_done.imageset/checkBox_done@2x.png
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_done.imageset/checkBox_done@3x.png
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_none.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_none.imageset/checkBox_none.png
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_none.imageset/checkBox_none@2x.png
  teamplan/Resources/Assets.xcassets/Images/Project/checkBox_none.imageset/checkBox_none@3x.png
  teamplan/Sources/Model/ProjectModel.swift
  teamplan/Sources/ViewModels/ProjectViewModel.swift
  teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
  teamplan/Sources/Views/Project/AddProjectView.swift
  teamplan/Sources/Views/Project/ProjectDetailView.swift
  teamplan/Sources/Views/Project/ProjectMainView.swift
  teamplan/Sources/Views/Project/ProjectView.swift
  teamplan/Sources/Views/Project/SubViews/ProjectCardView.swift
  teamplan/Sources/Views/Project/SubViews/ToDoView.swift
Labels: For: iOS Dev, Priority: Medium, Status: Complete
