Repository 1OS-DevTeam/TodoPang, pull requests merged in 2024-05, with the labels that each got.

#96 [refact][add] Merge Mypage Service & View, Add AutoLogin feature
  teamplan/Sources/App/TeamPlanApp.swift
  teamplan/Sources/Object/UserObject.swift
  teamplan/Sources/Protocol/CoreDataManaging.swift
  teamplan/Sources/Protocol/FireStoreManaging.swift
  teamplan/Sources/Protocol/ServiceError.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
  teamplan/Sources/Services/Challenge/ChallengeServicesFirestore.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/CoreValue/CoreValueServicesCoredata.swift
  teamplan/Sources/Services/CoreValue/CoreValueServicesFirestore.swift
  teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
  teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
  teamplan/Sources/Services/Login/AuthAppleService.swift
  teamplan/Sources/Services/Login/AuthGoogleService.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/LoginService.swift
  teamplan/Sources/Services/MypageService.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/Sources/Services/Project/ProjectServicesFirestore.swift
  teamplan/Sources/Services/Project/TodoServicesCoredata.swift
  teamplan/Sources/Services/ProjectService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
  teamplan/Sources/Services/Synchronize/SyncLocalWithServer.swift
  teamplan/Sources/Services/Synchronize/SyncServerWithLocal.swift
  teamplan/Sources/Services/User/UserServicesCoredata.swift
  teamplan/Sources/Services/User/UserServicesFirestore.swift
  teamplan/Sources/Util/UserDefaultManager.swift
  teamplan/Sources/Util/Utilities.swift
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
  teamplan/Sources/ViewModels/MypageViewModel.swift
  teamplan/Sources/Views/Home/HomeView.swift
  teamplan/Sources/Views/MyPage/MyPageView.swift
  teamplan/Sources/Views/Onboarding/IntroView.swift
  teamplan/Sources/Views/Project/ProjectView.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature, Type: Refactoring

#98 [refact] Home(View, ViewModel, Service) & ETC
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/Sources/Util/Utilities.swift
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
  teamplan/Sources/Views/Home/HomeView.swift
  teamplan/Sources/Views/Home/SubView/MyChallengeView.swift
  teamplan/Sources/Views/Home/SubView/MyProjectView.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature, Type: Refactoring

#99 [Feat] Update Styling for Launch Screen and Onboarding View
  teamplan/Resources/Images.xcassets/LaunchScreen/todopang_logo.imageset/Contents.json
  teamplan/Resources/Images.xcassets/LaunchScreen/todopang_logo.imageset/todopang_logo.png
  teamplan/Resources/Images.xcassets/LaunchScreen/todopang_logo.imageset/todopang_logo@2x.png
  teamplan/Resources/Images.xcassets/LaunchScreen/todopang_logo.imageset/todopang_logo@3x.png
  teamplan/Resources/Images.xcassets/New Folder/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description1.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description1.imageset/onboarding_description1.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description1.imageset/onboarding_description1@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description1.imageset/onboarding_description1@3x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description2.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description2.imageset/onboarding_description2.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description2.imageset/onboarding_description2@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description2.imageset/onboarding_description2@3x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description3.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description3.imageset/onboarding_description3.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description3.imageset/onboarding_description3@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description3.imageset/onboarding_description3@3x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description4.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description4.imageset/onboarding_description4.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description4.imageset/onboarding_description4@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_description4.imageset/onboarding_description4@3x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image1.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image1.imageset/onboarding_image1.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image1.imageset/onboarding_image1@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image1.imageset/onboarding_image1@3X.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image2.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image2.imageset/onboarding_image2.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image2.imageset/onboarding_image2@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image2.imageset/onboarding_image2@3x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image3.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image3.imageset/onboarding_image3.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image3.imageset/onboarding_image3@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image3.imageset/onboarding_image3@3x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image4.imageset/Contents.json
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image4.imageset/onboarding_image4.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image4.imageset/onboarding_image4@2x.png
  teamplan/Resources/Images.xcassets/Onboarding/onboarding_image4.imageset/onboarding_image4@3x.png
  teamplan/Resources/Launch/LaunchScreen.storyboard
  teamplan/Sources/AutoGenerated/Assets.swift
  teamplan/Sources/Views/Onboarding/OnboardingView.swift
Labels: For: iOS Dev

#101 [feat] Add Background Task
  teamplan/Info.plist
  teamplan/Sources/App/TeamPlanApp.swift
  teamplan/Sources/Protocol/CoreDataManaging.swift
  teamplan/Sources/Services/Project/ProjectServicesBackground.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/teamplan.entitlements
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature
