Repository 1OS-DevTeam/TodoPang, pull requests merged in 2024-01, with the labels that each got.

#58 [feat] Add Duplicated Check & Update function to 'ChallengeService'
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Project/ProjectDTO.swift
  teamplan/Sources/Object/Project/ProjectObject.swift
  teamplan/Sources/Object/Statistics/StatisticsDTO.swift
  teamplan/Sources/Services/Challenge/ChallengeManager.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/Services/Data/NotificationDataService.swift
  teamplan/Sources/Services/Data/SignupDataService.swift
  teamplan/Sources/Services/Data/TermsDataService.swift
  teamplan/Sources/Services/LoginLoadingService.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/Sources/Services/ProjectIndexService.swift
  teamplan/Sources/Services/SignupLoadingService.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardBackView.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#60 [fix] fix bug in challengesView
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Object/Challenge/ChallengeObject.swift
  teamplan/Sources/Services/ChallengeService.swift
  teamplan/Sources/ViewModels/HomeViewModel.swift
  teamplan/Sources/Views/Alert/ChallengeAlertView.swift
  teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardFrontView.swift
  teamplan/Sources/Views/Home/HomeView.swift
Labels: For: iOS Dev, Priority: High

#59 [feat] Add 'ProjectDetailService' and Support Function
  teamplan/Resources/Storage/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
  teamplan/Sources/Object/Project/ProjectDTO.swift
  teamplan/Sources/Object/Project/ProjectObject.swift
  teamplan/Sources/Object/Project/TodoDTO.swift
  teamplan/Sources/Object/Project/TodoObject.swift
  teamplan/Sources/Object/Statistics/StatisticsDTO.swift
  teamplan/Sources/Object/Statistics/StatisticsObject.swift
  teamplan/Sources/Services/HomeService.swift
  teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
  teamplan/Sources/Services/Project/TodoServicesCoredata.swift
  teamplan/Sources/Services/ProjectDetailService.swift
  teamplan/Sources/Services/ProjectIndexService.swift
  teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
  teamplan/Sources/Util/Utilities.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Feature

#62 [feat] add alerts and add my challenges view in HomeView
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_blue.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_blue.imageset/alert_didChallenge_rectangle_blue.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_blue.imageset/alert_didChallenge_rectangle_blue@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_blue.imageset/alert_didChallenge_rectangle_blue@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_grey.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_grey.imageset/alert_didChallenge_rectangle_grey.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_grey.imageset/alert_didChallenge_rectangle_grey@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_grey.imageset/alert_didChallenge_rectangle_grey@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_plus.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_plus.imageset/alert_didChallenge_rectangle_plus.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_plus.imageset/alert_didChallenge_rectangle_plus@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_rectangle_plus.imageset/alert_didChallenge_rectangle_plus@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_red.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_red.imageset/alert_didChallenge_red.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_red.imageset/alert_didChallenge_red@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_red.imageset/alert_didChallenge_red@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_x.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_x.imageset/alert_didChallenge_x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_x.imageset/alert_didChallenge_x@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_x.imageset/alert_didChallenge_x@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow1.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow1.imageset/alert_didChallenge_yellow1.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow1.imageset/alert_didChallenge_yellow1@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow1.imageset/alert_didChallenge_yellow1@3x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow2.imageset/Contents.json
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow2.imageset/alert_didChallenge_yellow2.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow2.imageset/alert_didChallenge_yellow2@2x.png
  teamplan/Resources/Assets.xcassets/Images/Home/Alert/alert_didChallenge_yellow2.imageset/alert_didChallenge_yellow2@3x.png
  teamplan/Sources/Object/Challenge/ChallengeDTO.swift
  teamplan/Sources/Util/ChallengeIconHelper.swift
  teamplan/Sources/Views/Alert/ChallengeAlertView.swift
  teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardBackView.swift
  teamplan/Sources/Views/Home/HomeView.swift
Labels: For: iOS Dev, Priority: Medium, Type: Feature
