Repository 1OS-DevTeam/TodoPang, pull requests merged in 2024-07, with the labels that each got.

#108 [fix] some features..
  Project.swift
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/1024.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/114.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/120.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/180.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/29.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/40.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/57.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/58.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/60.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/80.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/87.png
  teamplan/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
  teamplan/Sources/Services/MypageService.swift
  teamplan/Sources/ViewModels/ProjectViewModel.swift
  teamplan/Sources/Views/Alert/ChallengeAlertView.swift
  teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
  teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardBackView.swift
  teamplan/Sources/Views/Home/SubView/MyProjectCardView.swift
  teamplan/Sources/Views/MyPage/MyPageView.swift
  teamplan/Sources/Views/Project/ProjectDetailView.swift
  teamplan/Sources/Views/Project/ProjectView.swift
  teamplan/Sources/Views/Project/SubViews/ProjectCardView.swift
Labels: For: iOS Dev

#113 [refact][feat] 20240717_Patch_Note
  teamplan/Sources/Services/ProjectService.swift
Labels: For: iOS Dev, Priority: Medium, Status: Review Needed, Type: Refactoring

#114 [debug] 20240718 HotFix about appleSocialLogin
  teamplan/Sources/ViewModels/AuthenticationViewModel.swift
  teamplan/Sources/Views/Authentication/LoginView.swift
Labels: For: iOS Dev, Priority: High, Status: Review Needed, Type: Bug
